### PR TITLE
fix: Fix frontend layout

### PR DESCRIPTION
**Pull request by bia1708**
`MainPage` did not fill up the entire screen, so I fixed that.
Modified the `MainPage` and the `SearchBar` components so that they look like the provided design. 
There is no more `SearchButton`, as there wasn't any in the provided design.
Also cleaned up code, removing unnecessary bits and pieces.

Frontend project used to look like this:
image

Frontend project now looks like this:
image

### CODE REVIEW

**Comment by Sipos-Lucas-George** [comment]
Good job, it looks great but a bit bland, in the near future i would suggest to modify the tabs, e.g. Instagram, Facebook, X. Meaning to make them stand out a bit, I know it is just layout but still, it looks like there is just text thrown in the canvas.

**Comment by bia1708** [comment]
@Sipos-Lucas-George The tabs do stand out, if you hover over them. That didn't show up in the screenshot for some reason, though.

**Review by Andrei-Fabian-Pop — APPROVED** [review]

**Comment by Sipos-Lucas-George** [comment]
@bia1708 Still a little bland but for the moment everything is alri :zap:

**Comment by bia1708** [comment]
@Sipos-Lucas-George I modified it so that the background for that component is now white. Here is the updated version:
image

**Comment by Andrei-Fabian-Pop** [comment]
The site looks really good for now, one minor detail we could add is the logo for Facebook, Instagram and X next to their names as that X there looks off. Even without this, it looks like a really good base for starting the development. 👍

**Comment by bia1708** [comment]
@Andrei-Fabian-Pop Maybe in another PR. I do not have the energy to do that right now :))

**Comment by Andrei-Fabian-Pop** [comment]
I have no problem with adding this only later, I think you can merge this @bia1708

**Comment by bia1708** [comment]
@Andrei-Fabian-Pop I'll wait a couple more hours, maybe @martinicolaevlad can have a look by then.

**Comment by bia1708** [comment]
Another update (added default gray bottom margin):
image

**Pull request merged**
